// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/controlplane/v1/fleet.proto

package fleetpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway_id is the stable, operator-assigned identity of the instance.
	GatewayId string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// version is the gateway binary version (e.g. "v1.2.0-33-ga0e761c").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// labels are arbitrary operator metadata (cluster, role, ...), surfaced in
	// the fleet console.
	Labels        map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// registered_at is the control plane's view of when this gateway first
	// appeared, RFC3339. Informational.
	RegisteredAt  string `protobuf:"bytes,1,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gateway_id identifies the heartbeating instance.
	GatewayId string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// version is re-reported every heartbeat so a rolling upgrade is visible in
	// the console without waiting for a re-register.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// cached_config_hashes are the content hashes of the configuration closures
	// the gateway currently holds. Phase 1 records them for forward-compat;
	// Phase 2 diffs them server-side to drive stale-config notifications.
	CachedConfigHashes []string `protobuf:"bytes,3,rep,name=cached_config_hashes,json=cachedConfigHashes,proto3" json:"cached_config_hashes,omitempty"`
	// labels may change across a gateway's lifetime; the latest set wins.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetCachedConfigHashes() []string {
	if x != nil {
		return x.CachedConfigHashes
	}
	return nil
}

func (x *HeartbeatRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controlplane_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_controlplane_v1_fleet_proto_rawDescGZIP(), []int{3}
}

var File_proto_controlplane_v1_fleet_proto protoreflect.FileDescriptor

const file_proto_controlplane_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"!proto/controlplane/v1/fleet.proto\x12\x16sluice.controlplane.v1\"\xd2\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12K\n" +
	"\x06labels\x18\x03 \x03(\v23.sluice.controlplane.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x10RegisterResponse\x12#\n" +
	"\rregistered_at\x18\x01 \x01(\tR\fregisteredAt\"\x86\x02\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x120\n" +
	"\x14cached_config_hashes\x18\x03 \x03(\tR\x12cachedConfigHashes\x12L\n" +
	"\x06labels\x18\x04 \x03(\v24.sluice.controlplane.v1.HeartbeatRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x11HeartbeatResponseJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\vrevocationsR\x10stale_config_ids2\xcf\x01\n" +
	"\fFleetService\x12]\n" +
	"\bRegister\x12'.sluice.controlplane.v1.RegisterRequest\x1a(.sluice.controlplane.v1.RegisterResponse\x12`\n" +
	"\tHeartbeat\x12(.sluice.controlplane.v1.HeartbeatRequest\x1a).sluice.controlplane.v1.HeartbeatResponseBMZKgithub.com/andyjmorgan/sluice-gateway/internal/controlplane/fleetpb;fleetpbb\x06proto3"

var (
	file_proto_controlplane_v1_fleet_proto_rawDescOnce sync.Once
	file_proto_controlplane_v1_fleet_proto_rawDescData []byte
)

func file_proto_controlplane_v1_fleet_proto_rawDescGZIP() []byte {
	file_proto_controlplane_v1_fleet_proto_rawDescOnce.Do(func() {
		file_proto_controlplane_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controlplane_v1_fleet_proto_rawDesc), len(file_proto_controlplane_v1_fleet_proto_rawDesc)))
	})
	return file_proto_controlplane_v1_fleet_proto_rawDescData
}

var file_proto_controlplane_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_controlplane_v1_fleet_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: sluice.controlplane.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 1: sluice.controlplane.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 2: sluice.controlplane.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: sluice.controlplane.v1.HeartbeatResponse
	nil,                       // 4: sluice.controlplane.v1.RegisterRequest.LabelsEntry
	nil,                       // 5: sluice.controlplane.v1.HeartbeatRequest.LabelsEntry
}
var file_proto_controlplane_v1_fleet_proto_depIdxs = []int32{
	4, // 0: sluice.controlplane.v1.RegisterRequest.labels:type_name -> sluice.controlplane.v1.RegisterRequest.LabelsEntry
	5, // 1: sluice.controlplane.v1.HeartbeatRequest.labels:type_name -> sluice.controlplane.v1.HeartbeatRequest.LabelsEntry
	0, // 2: sluice.controlplane.v1.FleetService.Register:input_type -> sluice.controlplane.v1.RegisterRequest
	2, // 3: sluice.controlplane.v1.FleetService.Heartbeat:input_type -> sluice.controlplane.v1.HeartbeatRequest
	1, // 4: sluice.controlplane.v1.FleetService.Register:output_type -> sluice.controlplane.v1.RegisterResponse
	3, // 5: sluice.controlplane.v1.FleetService.Heartbeat:output_type -> sluice.controlplane.v1.HeartbeatResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_controlplane_v1_fleet_proto_init() }
func file_proto_controlplane_v1_fleet_proto_init() {
	if File_proto_controlplane_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controlplane_v1_fleet_proto_rawDesc), len(file_proto_controlplane_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controlplane_v1_fleet_proto_goTypes,
		DependencyIndexes: file_proto_controlplane_v1_fleet_proto_depIdxs,
		MessageInfos:      file_proto_controlplane_v1_fleet_proto_msgTypes,
	}.Build()
	File_proto_controlplane_v1_fleet_proto = out.File
	file_proto_controlplane_v1_fleet_proto_goTypes = nil
	file_proto_controlplane_v1_fleet_proto_depIdxs = nil
}
